#!/usr/bin/env zsh

cols=5
if [[ $# -gt 0 ]] ; then
	case $1 in
		-*)	echo "Usage: $0 [columnum] < text" ; exit 1 ;;
	esac
	cols=$1 
fi

for index in .$$.{0..$cols} ; do
	rm -f $index ; touch $index
done

i=0
sed 's/[^A-Za-z0-9 ]//g' | 
	while read -r line ; do
		setopt shwordsplit
		for word in $line ; do
			echo "$word" >> .$$.$i
			i=$((i+1))
			if [[ $i -gt $cols ]] ; then 
				i=0 ; 
			fi
		done
		setopt noshwordsplit
	done

rm -f .$$ ; touch .$$
for index in .$$.{0..$cols} ; do
	paste .$$ <(shuf $index) > .$$.2 ; mv .$$.2 .$$
	rm -f $index ; touch $index
done
sed 's/	/ /g' < .$$
rm -f .$$

